#!/bin/bash

paste -d " " \
<(curl -s https://ucr.fbi.gov/crime-in-the-u.s/2016/crime-in-the-u.s.-2016/topic-pages/tables/table-1 | pup --color "div#table-data-container td.group2 text{}") \
<(curl -s https://ucr.fbi.gov/crime-in-the-u.s/2016/crime-in-the-u.s.-2016/topic-pages/tables/table-1 | pup --color "div#table-data-container td.group1 text{}") \
| sed 's/,//g;s/\s$//g;s/\s/,/g;/^$/d' | R --slave -e 'x <- file("stdin"); t <- read.csv(x); summary(t)'

